### ISSUE TITLE
ImportError: cannot import name 'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings'

### ISSUE THREAD

**Issue by Leehorywei** [chaojie/ComfyUI-AniPortrait#14]
Traceback (most recent call last):
  File "E:\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\custom_nodes\ComfyUI-AniPortrait\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "E:\ComfyUI\custom_nodes\ComfyUI-AniPortrait\nodes.py", line 28, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "E:\ComfyUI\custom_nodes\ComfyUI-AniPortrait\src\models\unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'GLIGENTextBoundingboxProjection' from 'diffusers.models.embeddings' (D:\anaconda3\envs\comfyui\lib\site-packages\diffusers\models\embeddings.py)

**Comment by Leehorywei** [comment]
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/29452107/c8764fd3-0d07-4724-a816-15d61b822bcb)

**Comment by Leehorywei** [comment]
upgrade to 0.27.2 is ok
