### ISSUE TITLE
PATH error that I can't solve

### ISSUE THREAD

**Issue by ShmuelRonen** [chaojie/ComfyUI-AniPortrait#16]
Hello and thank-you for the project!

What I do wrong?

E:\ComfyUI_4ALL>call conda activate comfyui

(comfyui) E:\ComfyUI_4ALL>python ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-04-01 08:36:10.943530
** Platform: Windows
** Python version: 3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)]
** Python executable: C:\Users\derec\anaconda3\envs\comfyui\python.exe
** Log path: E:\ComfyUI_4ALL\comfyui.log

E:\ComfyUI_4ALL\ComfyUI\models\diffusers\ZJYang\AniPortrait\pose_guider.pth
E:\ComfyUI_4ALL\ComfyUI\models\diffusers\stable-diffusion-v1-5
E:\ComfyUI_4ALL\ComfyU\models\diffusers\sd-vae-ft-mse
E:\ComfyUI_4ALL\ComfyUI\models\diffusers\facebook\wav2vec2-base-960h
E:\ComfyUI_4ALL\ComfyUI\models\diffusers\sd-image-variations-diffusers\image_encoder
E:\ComfyUI_4ALL\ComfyUI\models\diffusers\ZJYang\AniPortrait\audio2mesh.pt
E:\ComfyUI_4ALL\ComfyUI\models\diffusers\ZJYang\AniPortrait\motion_module.pth
E:\ComfyUI_4ALL\ComfyUI\models\diffusers\ZJYang\AniPortrait\denoising_unet.pth
E:\ComfyUI_4ALL\ComfyUI\models\diffusers\ZJYang\AniPortrait\reference_unet.pth

_____________

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ComfyUI_4ALL\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_4ALL\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_4ALL\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_4ALL\ComfyUI\custom_nodes\ComfyUI-AniPortrait\nodes.py", line 112, in run
    a2m_model = Audio2MeshModel(audio_infer_config['a2m_model'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_4ALL\ComfyUI\custom_nodes\ComfyUI-AniPortrait\src\audio_models\model.py", line 25, in __init__
    self.audio_encoder_config = Wav2Vec2Config.from_pretrained(model_path, local_files_only=True)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derec\anaconda3\envs\comfyui\Lib\site-packages\transformers\configuration_utils.py", line 602, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derec\anaconda3\envs\comfyui\Lib\site-packages\transformers\configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derec\anaconda3\envs\comfyui\Lib\site-packages\transformers\configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\Users\derec\anaconda3\envs\comfyui\Lib\site-packages\transformers\utils\hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '\ComfyUI_4ALL\ComfyUI\models\diffusers\facebook\wav2vec2-base-960h'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

Prompt executed in 0.18 seconds

**Comment by RYG81** [comment]
Have same issue, can you please mae kit select file option just like check point

**Comment by Pythonpa** [comment]
The same question,

**Comment by eldragon0** [comment]
I can say for sure, it works on windows.

**Comment by Aljnk** [comment]
change it here too
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/11256478/bff7c2f9-511b-4340-a987-0cc24aa4821f)

**Comment by DoItEric** [comment]
@Aljnk U SOOOOOOOOOOO GOOD

**Comment by invincibledinku** [comment]
still get the error, any fix to this?

**Comment by ShmuelRonen** [comment]
> still get the error, any fix to this?

I use this instead and it's working:

https://github.com/frankchieng/ComfyUI_Aniportrait
