### ISSUE TITLE
cannot import name 'PositionNet' from 'diffusers.models.embeddings' 

### ISSUE THREAD

**Issue by robbinhan** [chaojie/ComfyUI-AniPortrait#2]
```bash

Traceback (most recent call last):
  File "/data/robbin/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/robbin/ComfyUI/custom_nodes/ComfyUI-AniPortrait/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "/data/robbin/ComfyUI/custom_nodes/ComfyUI-AniPortrait/nodes.py", line 28, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "/data/robbin/ComfyUI/custom_nodes/ComfyUI-AniPortrait/src/models/unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (/home/ubuntu/miniconda3/envs/comfyui/lib/python3.10/site-packages/diffusers/models/embeddings.py)
```

my diffusers version is 0.27.2

**Comment by chaojie** [comment]
pip install diffusers==0.24.0

**Comment by chaojie** [comment]
the support for the new version of diffusers is now available.
