### ISSUE TITLE
Error occurred when executing AniPortraitLoader

### ISSUE THREAD

**Issue by lifeng5658** [chaojie/ComfyUI-AniPortrait#20]
Error occurred when executing AniPortraitLoader:

Error no file named config.json found in directory E:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-AniPortrait\pretrained_model\StableDiffusion V1.5\.

File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-AniPortrait\nodes.py", line 120, in run
reference_unet = UNet2DConditionModel.from_pretrained(
File "E:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "E:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\diffusers\models\modeling_utils.py", line 567, in from_pretrained
config, unused_kwargs, commit_hash = cls.load_config(
File "E:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "E:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\diffusers\configuration_utils.py", line 374, in load_config
raise EnvironmentError(

**Comment by nutschan** [comment]
I got the same problem,

Some weights of Wav2Vec2Model were not initialized from the model checkpoint at G:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AniPortrait\pretrained_model\wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "G:\AI\ComfyUI\ComfyUI\execution.py", line 221, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AniPortrait\nodes.py", line 120, in run
    reference_unet = UNet2DConditionModel.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 567, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 374, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory G:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AniPortrait\pretrained_model\stable-diffusion-v1-5.

Prompt executed in 55.69 seconds
